language: python

python:
  - 3.6.1

install: 
  - pip install -r requirements.txt
  - pip install coveralls
  
env:
  CODECLIMATE_REPO_TOKEN: 2a80915b247c484d8bd14ce7b8919789ab35f6c501390f8387610aaf69aa7d08

script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls

deploy:
  provider: heroku
  app: the-real-shopping-list
  api_key:
    secure: "f5329e27-168b-45dd-85f6-585c43c8a8d1"